{% set name = "hiplot" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6aa5635856656d6342839de5dc485dcbcd38cb0f238b95f95dae3020d182cc51

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - beautifulsoup4
    - flask
    - flask-compress
    - ipython >=7.0.1
    - python >=3.6

test:
  imports:
    - hiplot

about:
  home: https://github.com/facebookresearch/hiplot
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: High dimensional Interactive Plotting tool
  doc_url: https://facebookresearch.github.io/hiplot/

extra:
  recipe-maintainers:
    - rpanai
    - danthe3rd
