travis:
  secure:
    BINSTAR_TOKEN: VVgEmHoGatLLtZzFnfrCHNcUrMCVpfdTwZiNvAn3TrqJLAxdHptsoRfDV5cJ2xQXkd/wnKWsVwlG0AOgE1Qa4UhrsSQ75ck1B07qSYoPvKuOj6FCK6l88Jc5I65x6AUEoExeJwTcb89gwIxhvcakOaFDcsVHlPKYKYvaGJGQD2ANO7v8nbjr0Y33gfQzypL4DoKcUsun+K6CJoXGxGyisSXi5FzJ0oXlFkDIGDhSUUKFmmUzwMrQSq424OUxfxKjsnPSAsSxxtDCE7Hm+cqrKjclKU9cUqoNV7roNLpTLubisCBI0xaqZTcRKB+TqmCf37Y5lG1M1DuvTfrG1HLVafSDuHVuTjR8V1KOeJAxSjKUsfFySEEfA1RQneLa8WXe00z/5kBRLE7ayjaF9vojlLtRuTRZsWz8CuVUNkg3OdCVbLRRc+fimIf74ArHnvCAJBNGFwdh+5RAl3Gkyccd0XCBHvOjUvPehkaeNbtFYivoelllYibN6WA6+zadFCRwQO89jRiiR29ZHj5KvRu/0gA/9OroMtdI6gnpeC1vIlrLrhsF810f8NNQnnxwdx/reCfdlkCrdUyO7Gw6C/9gWt8Upc65k+38G7GPYK+fY0JfjB59enARaV4UuBPdaTGrOCOmBdTYkUVWjDxz3YVW6EbTMG6bPNsVXBLIHmuvLD0=
conda_forge_output_validation: true
bot:
  automerge: true
